### PR TITLE
Add Windows native authentication support

### PR DESCRIPTION
**Pull request by gentoo90**
Add kerberos-sspi as an alternative backend.
[kerberos-sspi](https://github.com/may-day/kerberos-sspi) package is an API level equivalent with kerberos
package but uses windows sspi (through pywin32)

### CODE REVIEW

**Comment by tardyp** [comment]
:+1: This PR fixes my windows kerberos authentication issues in a clean fashion. Please merge it!

**Comment by e-nouri** [comment]
+1 Kerberos SSPI fixed the issue on Windows, pealse merge it!

**Comment by mkomitee** [comment]
If it's not already clear from before, I'm +1.

**Comment by sigmavirus24** [comment]
@gentoo90 can you rebase this? It isn't mergeable in its present state

**Comment by gentoo90** [comment]
Done. Sorry for the delay.

**Comment by rbcarson** [comment]
@sigmavirus24 I'm in favour of this, and the changes look good to me. Right now I'm accomplishing the same result by renaming kerberos_sspi.py to kerberos.py.

**Comment by sigmavirus24** [comment]
Thanks for the :eyes: @rbcarson

**Pull request merged**
