### PR TITLE
Update .travis.yml to drop Python 3.3 and support Python 3.7

### PR DESCRIPTION
**Pull request by henry0312**

### CODE REVIEW

**Comment by mkomitee** [comment]
I'm not familiar with travis. What's the reason for switching to xenial?

Is there any reason to stop testing 3.3?

 It would be good to know when/if we want to merge a change that breaks 3.3 support. When that happens we can make the decision to officially drop support.

**Comment by mkomitee** [comment]
Oh, I see it already doesn't work from https://github.com/requests/requests-kerberos/pull/126.

**Comment by henry0312** [comment]
@mkomitee Because tests with Python 3.7 on Travis CI requires xenial.

**Comment by mkomitee** [comment]
Thanks for your contribution.

**Pull request merged**
